import AppKit

extension ThemeCatalog {
    static let presetGroupFour: [AppTheme] = [
        AppTheme(
            id: "obsidian-luxe",
            name: "Obsidian Luxe",
            symbolName: "sparkles.square.filled.on.square",
            panelGradient: [hex(0x0F1014), hex(0x262A34)],
            tileGradient: [hex(0x5F6677), hex(0x1C202B)],
            tileSecondaryGradient: [hex(0x7F8696), hex(0x343B4B)],
            panelBorder: hex(0xD8DEEA, alpha: 0.24),
            titleColor: hex(0xF6F7FB),
            bodyColor: hex(0xB7BFCE),
            closeFill: hex(0xFFFFFF, alpha: 0.08),
            closeTint: hex(0xF4F7FD),
            settingsFill: hex(0xFFFFFF, alpha: 0.1),
            settingsTint: hex(0xEFF2F8),
            badgeOnFill: hex(0xF4F7FD),
            badgeOnText: hex(0x232938),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.12),
            badgeOffText: hex(0xF7F9FD),
            titleFontName: preferredFontName("Avenir Next Heavy", "HelveticaNeue-Bold", fallback: "Avenir Next Heavy"),
            cardFontName: preferredFontName("Avenir Next Demi Bold", "HelveticaNeue-Medium", fallback: "Avenir Next Demi Bold")
        ),
        AppTheme(
            id: "champagne-editorial",
            name: "Champagne Editorial",
            symbolName: "text.book.closed.fill",
            panelGradient: [hex(0xFFF6EA), hex(0xE8D7C2)],
            tileGradient: [hex(0xA67C52), hex(0x705239)],
            tileSecondaryGradient: [hex(0xC09362), hex(0x8B6648)],
            panelBorder: hex(0xFFFDF8, alpha: 0.9),
            titleColor: hex(0x382416),
            bodyColor: hex(0x6B5241),
            closeFill: hex(0xFFF8F0, alpha: 0.76),
            closeTint: hex(0x6E4A31),
            settingsFill: hex(0xFFF9F2, alpha: 0.8),
            settingsTint: hex(0x5D3D28),
            badgeOnFill: hex(0xFFF9F0),
            badgeOnText: hex(0x845939),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.2),
            badgeOffText: hex(0xFFFDF8),
            titleFontName: preferredFontName("Didot-Bold", "Baskerville-Bold", fallback: "Didot-Bold"),
            cardFontName: preferredFontName("Avenir Next Demi Bold", "GillSans-SemiBold", fallback: "Avenir Next Demi Bold")
        ),
        AppTheme(
            id: "jade-reserve",
            name: "Jade Reserve",
            symbolName: "seal.fill",
            panelGradient: [hex(0xE7F3ED), hex(0xC8DBC9)],
            tileGradient: [hex(0x2C6A56), hex(0x183C32)],
            tileSecondaryGradient: [hex(0x4A8B74), hex(0x245243)],
            panelBorder: hex(0xF6FFF9, alpha: 0.84),
            titleColor: hex(0x17352C),
            bodyColor: hex(0x4D6E63),
            closeFill: hex(0xF3FFF7, alpha: 0.74),
            closeTint: hex(0x295A49),
            settingsFill: hex(0xF4FFF8, alpha: 0.76),
            settingsTint: hex(0x234D40),
            badgeOnFill: hex(0xF5FFF8),
            badgeOnText: hex(0x32604F),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFAFFFC),
            titleFontName: preferredFontName("Palatino-Bold", "Georgia-Bold", fallback: "Palatino-Bold"),
            cardFontName: preferredFontName("Avenir Next Demi Bold", "Optima-Bold", fallback: "Avenir Next Demi Bold")
        ),
        AppTheme(
            id: "cobalt-signature",
            name: "Cobalt Signature",
            symbolName: "staroflife.fill",
            panelGradient: [hex(0xE9F0FF), hex(0xC5D8F8)],
            tileGradient: [hex(0x2D63C8), hex(0x1B2F70)],
            tileSecondaryGradient: [hex(0x4B8AE6), hex(0x2D58AD)],
            panelBorder: hex(0xF7FAFF, alpha: 0.88),
            titleColor: hex(0x1A2F59),
            bodyColor: hex(0x506789),
            closeFill: hex(0xF7FBFF, alpha: 0.76),
            closeTint: hex(0x33518F),
            settingsFill: hex(0xF7FAFF, alpha: 0.78),
            settingsTint: hex(0x28447B),
            badgeOnFill: hex(0xF7FAFF),
            badgeOnText: hex(0x35569A),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.2),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: preferredFontName("Optima-Bold", "HelveticaNeue-Bold", fallback: "Optima-Bold"),
            cardFontName: preferredFontName("Avenir Next Bold", "HelveticaNeue-Medium", fallback: "Avenir Next Bold")
        ),
        AppTheme(
            id: "ruby-parlor",
            name: "Ruby Parlor",
            symbolName: "seal.fill",
            panelGradient: [hex(0xFBE7EA), hex(0xD9A4AF)],
            tileGradient: [hex(0x8D2F42), hex(0x5B1224)],
            tileSecondaryGradient: [hex(0xB94A63), hex(0x81283E)],
            panelBorder: hex(0xFFF4F5, alpha: 0.86),
            titleColor: hex(0x451625),
            bodyColor: hex(0x73505B),
            closeFill: hex(0xFFF3F5, alpha: 0.74),
            closeTint: hex(0x803346),
            settingsFill: hex(0xFFF5F6, alpha: 0.76),
            settingsTint: hex(0x6F283A),
            badgeOnFill: hex(0xFFF5F7),
            badgeOnText: hex(0x7E3245),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFFF9FA),
            titleFontName: preferredFontName("Baskerville-Bold", "Didot-Bold", fallback: "Baskerville-Bold"),
            cardFontName: preferredFontName("Avenir Next Demi Bold", "GillSans-SemiBold", fallback: "Avenir Next Demi Bold")
        ),
        AppTheme(
            id: "seaside-ledger",
            name: "Seaside Ledger",
            symbolName: "sailboat.fill",
            panelGradient: [hex(0xE6F6F4), hex(0xCBE7E0)],
            tileGradient: [hex(0x1E7581), hex(0x144A5D)],
            tileSecondaryGradient: [hex(0x2FA4A1), hex(0x236C7D)],
            panelBorder: hex(0xF4FFFD, alpha: 0.88),
            titleColor: hex(0x163B48),
            bodyColor: hex(0x4A6970),
            closeFill: hex(0xF1FFFD, alpha: 0.76),
            closeTint: hex(0x2A6670),
            settingsFill: hex(0xF3FFFD, alpha: 0.78),
            settingsTint: hex(0x225A63),
            badgeOnFill: hex(0xF3FFFE),
            badgeOnText: hex(0x2C6970),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.2),
            badgeOffText: hex(0xFBFFFF),
            titleFontName: preferredFontName("GillSans-Bold", "Optima-Bold", fallback: "GillSans-Bold"),
            cardFontName: preferredFontName("GillSans-SemiBold", "Avenir Next Demi Bold", fallback: "GillSans-SemiBold")
        ),
        AppTheme(
            id: "plum-atelier",
            name: "Plum Atelier",
            symbolName: "scribble.variable",
            panelGradient: [hex(0xF5EBFB), hex(0xDAC3EB)],
            tileGradient: [hex(0x6C3E79), hex(0x352041)],
            tileSecondaryGradient: [hex(0x8A5CA0), hex(0x523268)],
            panelBorder: hex(0xFFF7FF, alpha: 0.84),
            titleColor: hex(0x331D3D),
            bodyColor: hex(0x6A5578),
            closeFill: hex(0xFFF7FF, alpha: 0.74),
            closeTint: hex(0x6A497D),
            settingsFill: hex(0xFFF8FF, alpha: 0.76),
            settingsTint: hex(0x5A3E6C),
            badgeOnFill: hex(0xFFF7FF),
            badgeOnText: hex(0x694B80),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFFF9FF),
            titleFontName: preferredFontName("HoeflerText-Black", "Didot-Bold", fallback: "HoeflerText-Black"),
            cardFontName: preferredFontName("Avenir Next Demi Bold", "HelveticaNeue-Medium", fallback: "Avenir Next Demi Bold")
        ),
        AppTheme(
            id: "studio-silver",
            name: "Studio Silver",
            symbolName: "circle.lefthalf.filled",
            panelGradient: [hex(0xF1F3F7), hex(0xD5D9E1)],
            tileGradient: [hex(0x7A8696), hex(0x434C5A)],
            tileSecondaryGradient: [hex(0x98A4B4), hex(0x5C6776)],
            panelBorder: hex(0xFFFFFF, alpha: 0.88),
            titleColor: hex(0x242B34),
            bodyColor: hex(0x566270),
            closeFill: hex(0xFAFBFD, alpha: 0.78),
            closeTint: hex(0x4D5866),
            settingsFill: hex(0xFBFCFE, alpha: 0.8),
            settingsTint: hex(0x414A57),
            badgeOnFill: hex(0xFFFFFF),
            badgeOnText: hex(0x4A5564),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.22),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: preferredFontName("HelveticaNeue-Bold", "Avenir Next Demi Bold", fallback: "HelveticaNeue-Bold"),
            cardFontName: preferredFontName("HelveticaNeue-Medium", "Avenir Next Medium", fallback: "HelveticaNeue-Medium")
        ),
        AppTheme(
            id: "atlas-ink",
            name: "Atlas Ink",
            symbolName: "globe.americas.fill",
            panelGradient: [hex(0xEAEFF4), hex(0xC9D3E0)],
            tileGradient: [hex(0x203A5A), hex(0x152235)],
            tileSecondaryGradient: [hex(0x365F91), hex(0x213D62)],
            panelBorder: hex(0xF8FBFF, alpha: 0.86),
            titleColor: hex(0x162637),
            bodyColor: hex(0x4C5C6F),
            closeFill: hex(0xF7FBFF, alpha: 0.76),
            closeTint: hex(0x2B486B),
            settingsFill: hex(0xF8FBFE, alpha: 0.78),
            settingsTint: hex(0x223E5E),
            badgeOnFill: hex(0xF7FBFF),
            badgeOnText: hex(0x2A486C),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFAFCFF),
            titleFontName: preferredFontName("AmericanTypewriter-Bold", "Baskerville-Bold", fallback: "AmericanTypewriter-Bold"),
            cardFontName: preferredFontName("Avenir Next Demi Bold", "GillSans-SemiBold", fallback: "Avenir Next Demi Bold")
        ),
        AppTheme(
            id: "pearl-nocturne",
            name: "Pearl Nocturne",
            symbolName: "moonphase.waning.gibbous.inverse",
            panelGradient: [hex(0xFFFDF8), hex(0xE4DDD4)],
            tileGradient: [hex(0x4D5C6A), hex(0x232B34)],
            tileSecondaryGradient: [hex(0x6E8295), hex(0x34414D)],
            panelBorder: hex(0xFFFFFF, alpha: 0.9),
            titleColor: hex(0x29323A),
            bodyColor: hex(0x5A6870),
            closeFill: hex(0xFFFDF9, alpha: 0.78),
            closeTint: hex(0x47535D),
            settingsFill: hex(0xFFFDF9, alpha: 0.8),
            settingsTint: hex(0x3C4953),
            badgeOnFill: hex(0xFFFFFF),
            badgeOnText: hex(0x45545F),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: preferredFontName("Georgia-Bold", "Palatino-Bold", fallback: "Georgia-Bold"),
            cardFontName: preferredFontName("Avenir Next Demi Bold", "HelveticaNeue-Medium", fallback: "Avenir Next Demi Bold")
        )
    ]
}
