import AppKit

extension ThemeCatalog {
    static let presetGroupThree: [AppTheme] = [
        AppTheme(
            id: "lavender-breeze",
            name: "Lavender Breeze",
            symbolName: "wind",
            panelGradient: [hex(0xF4EEFF), hex(0xE5D6FF)],
            tileGradient: [hex(0x9A74F8), hex(0x5E53C4)],
            tileSecondaryGradient: [hex(0xB089F7), hex(0x7268D5)],
            panelBorder: hex(0xFFF9FF, alpha: 0.86),
            titleColor: hex(0x352853),
            bodyColor: hex(0x685A8A),
            closeFill: hex(0xFFF8FF, alpha: 0.74),
            closeTint: hex(0x625190),
            settingsFill: hex(0xFFF8FF, alpha: 0.76),
            settingsTint: hex(0x554581),
            badgeOnFill: hex(0xFFF8FF),
            badgeOnText: hex(0x654E97),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: "HoeflerText-Black",
            cardFontName: "GillSans-SemiBold"
        ),
        AppTheme(
            id: "oceanic-signal",
            name: "Oceanic Signal",
            symbolName: "waveform.path.ecg",
            panelGradient: [hex(0xDBF7FF), hex(0xB7E1E8)],
            tileGradient: [hex(0x157A8C), hex(0x1A4E73)],
            tileSecondaryGradient: [hex(0x2898A9), hex(0x215B8A)],
            panelBorder: hex(0xF2FFFF, alpha: 0.88),
            titleColor: hex(0x13384D),
            bodyColor: hex(0x40606E),
            closeFill: hex(0xF4FFFF, alpha: 0.76),
            closeTint: hex(0x2A5D73),
            settingsFill: hex(0xF4FFFF, alpha: 0.78),
            settingsTint: hex(0x214C62),
            badgeOnFill: hex(0xF5FFFF),
            badgeOnText: hex(0x285C70),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: "TrebuchetMS-Bold",
            cardFontName: "Trebuchet-BoldItalic"
        ),
        AppTheme(
            id: "golden-hour",
            name: "Golden Hour",
            symbolName: "sunset.fill",
            panelGradient: [hex(0xFFF2D8), hex(0xF6C17D)],
            tileGradient: [hex(0xD47630), hex(0x8A4320)],
            tileSecondaryGradient: [hex(0xEBA14F), hex(0xB9622F)],
            panelBorder: hex(0xFFF9EE, alpha: 0.88),
            titleColor: hex(0x4E250E),
            bodyColor: hex(0x7C4A28),
            closeFill: hex(0xFFF7E7, alpha: 0.74),
            closeTint: hex(0x77421D),
            settingsFill: hex(0xFFF7E7, alpha: 0.76),
            settingsTint: hex(0x6A3A18),
            badgeOnFill: hex(0xFFF9EE),
            badgeOnText: hex(0x8A4B21),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.2),
            badgeOffText: hex(0xFFFDF7),
            titleFontName: "AmericanTypewriter-Bold",
            cardFontName: "AmericanTypewriter-Semibold"
        ),
        AppTheme(
            id: "forest-club",
            name: "Forest Club",
            symbolName: "tree.fill",
            panelGradient: [hex(0xE7F0E7), hex(0xAFC2A2)],
            tileGradient: [hex(0x315942), hex(0x1E3528)],
            tileSecondaryGradient: [hex(0x557C61), hex(0x294836)],
            panelBorder: hex(0xF4FFF0, alpha: 0.8),
            titleColor: hex(0x1D3124),
            bodyColor: hex(0x4C6254),
            closeFill: hex(0xF7FFF3, alpha: 0.72),
            closeTint: hex(0x33513E),
            settingsFill: hex(0xF7FFF3, alpha: 0.74),
            settingsTint: hex(0x2D4837),
            badgeOnFill: hex(0xF6FFF4),
            badgeOnText: hex(0x355643),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.16),
            badgeOffText: hex(0xF8FFF6),
            titleFontName: "Georgia-Bold",
            cardFontName: "Georgia-Bold"
        ),
        AppTheme(
            id: "candy-signal",
            name: "Candy Signal",
            symbolName: "heart.circle.fill",
            panelGradient: [hex(0xFFEAF4), hex(0xFFD1E6)],
            tileGradient: [hex(0xFF5A8A), hex(0xFF8A5B)],
            tileSecondaryGradient: [hex(0xFF84A8), hex(0xFFAA5B)],
            panelBorder: hex(0xFFF9FD, alpha: 0.86),
            titleColor: hex(0x5F2341),
            bodyColor: hex(0x85576E),
            closeFill: hex(0xFFF8FB, alpha: 0.74),
            closeTint: hex(0x8B3D62),
            settingsFill: hex(0xFFF8FB, alpha: 0.76),
            settingsTint: hex(0x7A3255),
            badgeOnFill: hex(0xFFF8FB),
            badgeOnText: hex(0x8B4563),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.2),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: "ChalkboardSE-Bold",
            cardFontName: "Chalkboard-Bold"
        )
    ]
}
