import AppKit

extension ThemeCatalog {
    static let presetGroupTwo: [AppTheme] = [
        AppTheme(
            id: "ice-panel",
            name: "Ice Panel",
            symbolName: "snowflake",
            panelGradient: [hex(0xF6FBFF), hex(0xDDEBF8)],
            tileGradient: [hex(0x78B8E8), hex(0x4E74B8)],
            tileSecondaryGradient: [hex(0x8ED9F7), hex(0x5A8BD0)],
            panelBorder: hex(0xFFFFFF, alpha: 0.94),
            titleColor: hex(0x1B3655),
            bodyColor: hex(0x3E5671),
            closeFill: hex(0xFFFFFF, alpha: 0.78),
            closeTint: hex(0x3B5E8C),
            settingsFill: hex(0xFFFFFF, alpha: 0.8),
            settingsTint: hex(0x35567E),
            badgeOnFill: hex(0xFFFFFF),
            badgeOnText: hex(0x41648F),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.2),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: "Optima-Bold",
            cardFontName: "Optima-ExtraBlack"
        ),
        AppTheme(
            id: "ember-night",
            name: "Ember Night",
            symbolName: "flame.fill",
            panelGradient: [hex(0x251714), hex(0x4F2418)],
            tileGradient: [hex(0xB43E1D), hex(0x652217)],
            tileSecondaryGradient: [hex(0xD4601E), hex(0x8B2F16)],
            panelBorder: hex(0xFFB08B, alpha: 0.32),
            titleColor: hex(0xFFF2EB),
            bodyColor: hex(0xE9BBA7),
            closeFill: hex(0xFFFFFF, alpha: 0.09),
            closeTint: hex(0xFFF0E8),
            settingsFill: hex(0xFFFFFF, alpha: 0.11),
            settingsTint: hex(0xFFF3EA),
            badgeOnFill: hex(0xFFF1E8),
            badgeOnText: hex(0x7A2917),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.16),
            badgeOffText: hex(0xFFF6EF),
            titleFontName: "Baskerville-Bold",
            cardFontName: "Baskerville-SemiBold"
        ),
        AppTheme(
            id: "matcha-soft",
            name: "Matcha Soft",
            symbolName: "leaf.fill",
            panelGradient: [hex(0xEEF5E8), hex(0xD4E5C2)],
            tileGradient: [hex(0x6FA86D), hex(0x3D6F52)],
            tileSecondaryGradient: [hex(0x89BE74), hex(0x537C58)],
            panelBorder: hex(0xF8FFF3, alpha: 0.84),
            titleColor: hex(0x25402C),
            bodyColor: hex(0x4C6654),
            closeFill: hex(0xF7FFF0, alpha: 0.74),
            closeTint: hex(0x3B5F43),
            settingsFill: hex(0xF7FFF0, alpha: 0.76),
            settingsTint: hex(0x34563C),
            badgeOnFill: hex(0xF6FFF0),
            badgeOnText: hex(0x456545),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFAFFF4),
            titleFontName: "Palatino-Bold",
            cardFontName: "Avenir Next Demi Bold"
        ),
        AppTheme(
            id: "vapor-arc",
            name: "Vapor Arc",
            symbolName: "bolt.circle.fill",
            panelGradient: [hex(0xF0E5FF), hex(0xD9B8FF), hex(0xA7C6FF)],
            tileGradient: [hex(0x8357FF), hex(0x2E82FF)],
            tileSecondaryGradient: [hex(0xC04BFF), hex(0x6E78FF)],
            panelBorder: hex(0xFFF7FF, alpha: 0.82),
            titleColor: hex(0x261B53),
            bodyColor: hex(0x5A548A),
            closeFill: hex(0xFFFFFF, alpha: 0.72),
            closeTint: hex(0x4B3F89),
            settingsFill: hex(0xFFFFFF, alpha: 0.74),
            settingsTint: hex(0x433D7D),
            badgeOnFill: hex(0xFAF7FF),
            badgeOnText: hex(0x3D51A8),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: "HelveticaNeue-Bold",
            cardFontName: "HelveticaNeue-CondensedBlack"
        ),
        AppTheme(
            id: "titanium-neon",
            name: "Titanium Neon",
            symbolName: "dot.radiowaves.left.and.right",
            panelGradient: [hex(0x111317), hex(0x2A303A)],
            tileGradient: [hex(0x0FA3B1), hex(0x335CFF)],
            tileSecondaryGradient: [hex(0x00C9A7), hex(0x2774E8)],
            panelBorder: hex(0x99F5FF, alpha: 0.3),
            titleColor: hex(0xF6F9FF),
            bodyColor: hex(0xB7C4D5),
            closeFill: hex(0xFFFFFF, alpha: 0.08),
            closeTint: hex(0xF4FBFF),
            settingsFill: hex(0xFFFFFF, alpha: 0.1),
            settingsTint: hex(0xF2FBFF),
            badgeOnFill: hex(0xF1FDFF),
            badgeOnText: hex(0x1B5C78),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.12),
            badgeOffText: hex(0xF6FBFF),
            titleFontName: "Avenir Next Heavy",
            cardFontName: "Avenir Next Heavy"
        )
    ]
}
