import AppKit

extension ThemeCatalog {
    static let presetGroupOne: [AppTheme] = [
        AppTheme(
            id: "sandstone-modern",
            name: "Sandstone Modern",
            symbolName: "sun.max.fill",
            panelGradient: [hex(0xF2E7D9), hex(0xD8C0A6)],
            tileGradient: [hex(0xC99B70), hex(0x8B5E3C)],
            tileSecondaryGradient: [hex(0xD9B087), hex(0x9F704C)],
            panelBorder: hex(0xFFF8EE, alpha: 0.8),
            titleColor: hex(0x362518),
            bodyColor: hex(0x5E4631),
            closeFill: hex(0xFFF8EE, alpha: 0.68),
            closeTint: hex(0x5A3A24),
            settingsFill: hex(0xFFF8EE, alpha: 0.72),
            settingsTint: hex(0x4E3421),
            badgeOnFill: hex(0xFFF3E7),
            badgeOnText: hex(0x754A2E),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.2),
            badgeOffText: hex(0xFFF9F1),
            titleFontName: "Avenir Next Demi Bold",
            cardFontName: "Avenir Next Bold"
        ),
        AppTheme(
            id: "aurora-glass",
            name: "Aurora Glass",
            symbolName: "sparkles",
            panelGradient: [hex(0xDDF8FF), hex(0xC9D5FF), hex(0xE9D6FF)],
            tileGradient: [hex(0x4ED0D9), hex(0x6E5CF6)],
            tileSecondaryGradient: [hex(0x69E3C2), hex(0x4A8BFF)],
            panelBorder: hex(0xFFFFFF, alpha: 0.88),
            titleColor: hex(0x203052),
            bodyColor: hex(0x3C4A68),
            closeFill: hex(0xFFFFFF, alpha: 0.7),
            closeTint: hex(0x425686),
            settingsFill: hex(0xFFFFFF, alpha: 0.76),
            settingsTint: hex(0x304A82),
            badgeOnFill: hex(0xF7FFFE),
            badgeOnText: hex(0x285A85),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.22),
            badgeOffText: hex(0xFFFFFF),
            titleFontName: "Futura-Bold",
            cardFontName: "Avenir Next Heavy"
        ),
        AppTheme(
            id: "midnight-mono",
            name: "Midnight Mono",
            symbolName: "moon.fill",
            panelGradient: [hex(0x10141D), hex(0x242A37)],
            tileGradient: [hex(0x293040), hex(0x151A25)],
            tileSecondaryGradient: [hex(0x3B455A), hex(0x1F2634)],
            panelBorder: hex(0x6D7688, alpha: 0.45),
            titleColor: hex(0xF3F4F7),
            bodyColor: hex(0xB4BCCC),
            closeFill: hex(0xFFFFFF, alpha: 0.08),
            closeTint: hex(0xEFF2F9),
            settingsFill: hex(0xFFFFFF, alpha: 0.08),
            settingsTint: hex(0xF6F8FC),
            badgeOnFill: hex(0xEEF1F7),
            badgeOnText: hex(0x232938),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.1),
            badgeOffText: hex(0xF6F7FB),
            titleFontName: "Menlo-Bold",
            cardFontName: "Menlo-Bold"
        ),
        AppTheme(
            id: "citrus-pop",
            name: "Citrus Pop",
            symbolName: "sun.haze.fill",
            panelGradient: [hex(0xFFF3D4), hex(0xFFD88F)],
            tileGradient: [hex(0xFF8A34), hex(0xFFCE38)],
            tileSecondaryGradient: [hex(0xFFAF3E), hex(0xF4681D)],
            panelBorder: hex(0xFFF9EE, alpha: 0.9),
            titleColor: hex(0x5A2900),
            bodyColor: hex(0x7F4A13),
            closeFill: hex(0xFFF7E4, alpha: 0.78),
            closeTint: hex(0x8A410B),
            settingsFill: hex(0xFFF7E4, alpha: 0.8),
            settingsTint: hex(0x7D3900),
            badgeOnFill: hex(0xFFF8EC),
            badgeOnText: hex(0x8B4511),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.24),
            badgeOffText: hex(0xFFFDF6),
            titleFontName: "GillSans-Bold",
            cardFontName: "GillSans-SemiBold"
        ),
        AppTheme(
            id: "rose-studio",
            name: "Rose Studio",
            symbolName: "camera.aperture",
            panelGradient: [hex(0xF9E6EA), hex(0xE8B8C6)],
            tileGradient: [hex(0xD2678A), hex(0x894B7A)],
            tileSecondaryGradient: [hex(0xE08AA0), hex(0xA35587)],
            panelBorder: hex(0xFFF2F5, alpha: 0.86),
            titleColor: hex(0x4A2036),
            bodyColor: hex(0x6D4153),
            closeFill: hex(0xFFF2F5, alpha: 0.74),
            closeTint: hex(0x7D375A),
            settingsFill: hex(0xFFF2F5, alpha: 0.76),
            settingsTint: hex(0x652D49),
            badgeOnFill: hex(0xFFF5F7),
            badgeOnText: hex(0x7C3B58),
            badgeOffFill: hex(0xFFFFFF, alpha: 0.18),
            badgeOffText: hex(0xFFF8FB),
            titleFontName: "Didot-Bold",
            cardFontName: "Avenir Next Demi Bold"
        )
    ]
}
